#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: tatva desai
email: tatvadesai95@gmail.com
description: >-
  pathologically curious
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tatvadesai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tatvadesai
github_username: tatvadesai
linkedin_username: tatvadesai
# PostHog Analytics
posthog_api_key: phc_GeUcz0Ouu6G5M37lqn3AIpnciAQgRBmFHseXIM5gDS4
posthog_host: https://us.i.posthog.com

# Build settings
# theme: minima 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  essays:
    output: true
    permalink: /essays/:slug/

defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "essay"
